on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      martix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.11, 3.12]

    step: 
    - name: Checkout code 
      uses: actions/checkout@v4

    - name: set up python ${{ martix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ martix.python-version }}

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run tests
      run: |
        mkdir -p test-results
        pytest --junitxml=test-results/result.xml

    -name: upload test results
      uses: actions/upload-artifacts@v3
      with:
        name: test-results
        path: test-results/

    - name: Build project
      run: |
        mkdir -p build
        echo "THis is a build outout for python ${{ martix.python-version}} on ${{ martix.os}}">build/output.txt
    - name: build-aritfact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/

      download:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Checkout code 
          uses: actions/checkout@v4
        - name: download test results artifact
          uses: actions/download-artifact@v3
          with:
            name: test-results
            path: download-test-results/

        - name: download build artifacts
          uses: actions/download-artifact@v3
          with: 
            name: build-artifacts
            path: download-build artifacts/

        - name: display download test results
          run: cat download-test-results/result.xml

        - name: display download build artifacts
          run: cat download-build-artifacts/output.txt
            
        
